return {
  -- 'ThePrimeagen/99',
  -- dependencies = { 'nvim-treesitter/nvim-treesitter' },
  -- config = function()
  --   local nn = require '99'
  --   nn.setup {
  --     md_files = { 'AGENT.md' },
  --     completion = {
  --       source = 'cmp',
  --       custom_rules = { '~/.config/99/skills' },
  --     },
  --   }
  --
  --   -- Fill in function (uses Treesitter to detect function boundaries)
  --   vim.keymap.set('n', '<leader>9f', nn.fill_in_function, { desc = '99: Fill in function' })
  --   vim.keymap.set('n', '<leader>9F', nn.fill_in_function_prompt, { desc = '99: Fill in function with prompt' })
  --
  --   -- Visual selection transforms
  --   vim.keymap.set('x', '<leader>9v', nn.visual, { desc = '99: Transform selection' })
  --   vim.keymap.set('x', '<leader>9V', nn.visual_prompt, { desc = '99: Transform selection with prompt' })
  --
  --   -- Utilities
  --   vim.keymap.set('n', '<leader>9s', nn.stop_all_requests, { desc = '99: Stop all requests' })
  --   vim.keymap.set('n', '<leader>9i', nn.info, { desc = '99: Show info' })
  --   vim.keymap.set('n', '<leader>9l', nn.view_logs, { desc = '99: View logs' })
  -- end,
}
