return {
  -- 'goolord/alpha-nvim',
  -- dependencies = {
  --   'nvim-tree/nvim-web-devicons',
  -- },
  -- lazy = false,
  -- config = function()
  --   local alpha = require 'alpha'
  --   local dashboard = require 'alpha.themes.dashboard'
  --   -- Set header
  --   dashboard.section.header.val = {
  --     '                                                     ',
  --     '  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ',
  --     '  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║ ',
  --     '  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║ ',
  --     '  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ',
  --     '  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ',
  --     '  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ',
  --     '                                                     ',
  --   }
  --   dashboard.section.buttons.val = {
  --     dashboard.button('e', '  New file', '<cmd>ene<CR>'),
  --     dashboard.button('SPC s f', '󰈞  Find file'),
  --     dashboard.button('SPC s g', '󰊄  Live grep'),
  --     dashboard.button('SPC S s', '  Load session'),
  --     dashboard.button('SPC S S', '  List sessions'),
  --     dashboard.button('c', '  Configuration', '<cmd>cd ~/.config/nvim/ <CR>'),
  --     dashboard.button('u', '  Update plugins', '<cmd>Lazy sync<CR>'),
  --     dashboard.button('q', '󰅚  Quit', '<cmd>qa<CR>'),
  --   }
  --   alpha.setup(dashboard.config)
  -- end,
}
