-- return { -- Autoformat
--   'stevearc/conform.nvim',
--   event = { 'BufWritePre' },
--   cmd = { 'ConformInfo' },
--   ---@module "conform"
--   ---@type conform.setupOpts
--   opts = {},
--   init = function()
--     -- If you want the formatexpr, here is the place to set it
--   end,
-- }
return {}
