-- return {
--   'mfussenegger/nvim-dap',
--   dependencies = {
--     'rcarriga/nvim-dap-ui',
--     'nvim-neotest/nvim-nio',
--     'theHamsta/nvim-dap-virtual-text',
--     'williamboman/mason.nvim',
--     'mfussenegger/nvim-dap-python',
--   },
--   config = function()
--     local dap = require 'dap'
--     local ui = require 'dapui'
--
--     require('dapui').setup()
--     require('nvim-dap-virtual-text').setup()
--     require('dap-python').setup 'uv'
--
--     vim.keymap.set('n', '<space>p', dap.toggle_breakpoint, { desc = 'Toggle break[p]oint' })
--     vim.keymap.set('n', '<space>gr', dap.run_to_cursor, { desc = 'Debug: [r]un to cursor' })
--     -- Eval var under cursor
--     vim.keymap.set('n', '<space>?', function()
--       require('dapui').eval(nil, { enter = true })
--     end, { desc = 'Debug: Show var under cursor' })
--     vim.keymap.set('n', '<F1>', dap.continue)
--     vim.keymap.set('n', '<F2>', dap.step_into)
--     vim.keymap.set('n', '<F3>', dap.step_over)
--     vim.keymap.set('n', '<F4>', dap.step_out)
--     vim.keymap.set('n', '<F5>', dap.step_back)
--     vim.keymap.set('n', '<F13>', dap.restart)
--     dap.listeners.before.attach.dapui_config = function()
--       ui.open()
--     end
--     dap.listeners.before.launch.dapui_config = function()
--       ui.open()
--     end
--     dap.listeners.before.event_terminated.dapui_config = function()
--       ui.close()
--     end
--     dap.listeners.before.event_exited.dapui_config = function()
--       ui.close()
--     end
--   end,
-- }
return {}
